target("5.3.2.2", function()
	set_kind("binary")
	add_packages("opengl", "glfw", "assimp", "stb")
	add_deps("utils")

	set_targetdir("$(projectdir)/package/bin")
	add_files("**.cpp")

	after_build(function(target)
		local projectdir = os.projectdir()
		local sourcedir = target:scriptdir()
		local target_dir = path.join(projectdir, "package/shaders")
		os.mkdir(target_dir)
		os.cp(path.join(sourcedir, "*.vs"), target_dir)
		os.cp(path.join(sourcedir, "*.fs"), target_dir)
		os.cp(path.join(sourcedir, "*.gs"), target_dir)
	end)
	after_clean(function(target)
		os.tryrm("$(projectdir)/package/shaders/3.2.2.*.vs")
		os.tryrm("$(projectdir)/package/shaders/3.2.2.*.fs")
		os.tryrm("$(projectdir)/package/shaders/3.2.2.*.gs")
	end)
end)
